-- 1.
SELECT *
FROM JOB;

-- 2.
SELECT JOB_CODE, JOB_NAME
FROM JOB;

-- 3.
SELECT *
FROM DEPARTMENT;

-- 4. 
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

-- 5.
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

-- 6.
SELECT EMP_NAME, SALARY*12 연봉, (SALARY+(SALARY*NVL(BONUS,0)))*12 총수령액, ((SALARY+(SALARY*NVL(BONUS,0)))*12)-(SALARY*12*0.03) 실수령액
FROM EMPLOYEE;

-- 7. 
SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM EMPLOYEE
WHERE SAL_LEVEL = 'S1';

-- 8.
SELECT EMP_NAME, SALARY, ((SALARY+(SALARY*NVL(BONUS,0)))*12)-(SALARY*12*0.03) 실수령액, HIRE_DATE
FROM EMPLOYEE
WHERE ((SALARY+(SALARY*NVL(BONUS,0)))*12)-(SALARY*12*0.03) >= 50000000;

-- 9.
SELECT *
FROM EMPLOYEE
WHERE SALARY >= 4000000 AND JOB_CODE = 'J2';

-- 10.
SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D5') AND HIRE_DATE < TO_DATE(20220101);

-- 11.
SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN TO_DATE(900101) AND TO_DATE('001201');

-- 12.
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE ('%연');

-- 13.
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE ('010%');

-- 14.
SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE ('____^_%') ESCAPE '^' AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6') AND HIRE_DATE BETWEEN TO_DATE(900101) AND TO_DATE('001201') AND SALARY >= 2700000; 

-- 15. 
SELECT EMP_NAME 이름, EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6)))생년, EXTRACT(MONTH FROM TO_DATE(SUBSTR(EMP_NO, 1, 6)))생월, EXTRACT(DAY FROM TO_DATE(SUBSTR(EMP_NO, 1, 6)))생일
FROM EMPLOYEE;

-- 16.
SELECT EMP_NAME 이름, RPAD(SUBSTR(EMP_NO, 1, 8), 14, '*') 주민번호
FROM EMPLOYEE;

-- 17.
SELECT EMP_NAME, ABS(FLOOR(HIRE_DATE-SYSDATE)) 근무일수1, ABS(FLOOR(SYSDATE-HIRE_DATE)) 근무일수2
FROM EMPLOYEE;

-- 18.
SELECT *
FROM EMPLOYEE
WHERE MOD(EMP_ID, 2) = 1;

-- 19.
SELECT *
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE) >= 20;

-- 20.
SELECT EMP_NAME 이름, TO_CHAR(SALARY, 'L9,999,9999') 급여
FROM EMPLOYEE;

-- 21. !!!
SELECT EMP_NAME, DEPT_CODE, TO_CHAR(TO_DATE(SUBSTR(EMP_NO, 1, 6)), 'RR"년" MM"월" DD"일"')생년월일, EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 6)))나이,
       TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO, 1, 6), 'RRMMDD'))/12) 만나이
FROM EMPLOYEE;


-- 22. 
SELECT DECODE(DEPT_CODE, 'D5', '총무부', 'D6', '기획부', 'D9', '영업부')
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5', 'D6', 'D9');

-- 23.
SELECT EMP_NAME, SUBSTR(EMP_NO, 1, 6)주민번호앞자리, SUBSTR(EMP_NO, 8, 7)주민번호뒷자리, SUBSTR(EMP_NO, 1, 6) + SUBSTR(EMP_NO, 8, 7)
FROM EMPLOYEE
WHERE EMP_ID = 201;

-- 24.
SELECT DEPT_CODE, SUM(SALARY+(SALARY*BONUS))
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
GROUP BY DEPT_CODE;

-- 25. !!!
SELECT COUNT(*)"전체 직원 수",
        COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), 2001, 1, NULL)) "2001년",
        COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), 2002, 1, NULL)) "2002년", 
        COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), 2003, 1, NULL)) "2003년", 
        COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), 2004, 1, NULL)) "2004년" 
FROM EMPLOYEE;


