ALTER TABLE MESSAGE ADD RECEIVER NUMBER NOT NULL CONSTRAINT FK_MEMBER_TO_MESSAGE_2 REFERENCES MEMBER (USER_NO);
COMMENT ON COLUMN MESSAGE.RECEIVER IS '받는회원번호';
ALTER TABLE MESSAGE RENAME COLUMN USER_NO TO SENDER;